///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ContactsData {
/*
{
  "_id": "649390ecb59a7fae596fcd1b",
  "name": "muhammet",
  "email": "muhammetaydin1704@gmail.com",
  "profile_image": "image_649390ecb59a7fae596fcd1b.png"
} 
*/

  String? Id;
  String? name;
  String? email;
  String? profileImage;

  ContactsData({
    this.Id,
    this.name,
    this.email,
    this.profileImage,
  });
  ContactsData.fromJson(Map<String, dynamic> json) {
    Id = json['_id']?.toString();
    name = json['name']?.toString();
    email = json['email']?.toString();
    profileImage = json['profile_image']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = Id;
    data['name'] = name;
    data['email'] = email;
    data['profile_image'] = profileImage;
    return data;
  }
}

class Contacts {
/*
{
  "success": true,
  "dataCount": 2,
  "data": [
    {
      "_id": "649390ecb59a7fae596fcd1b",
      "name": "muhammet",
      "email": "muhammetaydin1704@gmail.com",
      "profile_image": "image_649390ecb59a7fae596fcd1b.png"
    }
  ]
} 
*/

  bool? success;
  int? dataCount;
  List<ContactsData?>? data;

  Contacts({
    this.success,
    this.dataCount,
    this.data,
  });
  Contacts.fromJson(Map<String, dynamic> json) {
    success = json['success'];
    dataCount = json['dataCount']?.toInt();
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ContactsData>[];
      v.forEach((v) {
        arr0.add(ContactsData.fromJson(v));
      });
      this.data = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['success'] = success;
    data['dataCount'] = dataCount;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['data'] = arr0;
    }
    return data;
  }
}
